backend:
  name: github
  repo: Amino47/ashellm.net # Path to your GitHub repository
  # optional, defaults to master
  branch: main
publish_mode: editorial_workflow
media_folder: "www/images/"
public_folder: "images"
site_url: https://ashellm.net
collections:
  - name: "notes" # Used in routes, e.g., /admin/collections/blog
    label: "Notes" # Used in the UI
    folder: "www/posts/notes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{month}}-{{day}}-{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/posts" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "articles" # Used in routes, e.g., /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "www/posts/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{month}}-{{day}}-{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/article" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "replies" # Used in routes, e.g., /admin/collections/blog
    label: "Replies" # Used in the UI
    folder: "www/posts/replies" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{month}}-{{day}}-{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/reply" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
